### ISSUE TITLE
Eksporteres automatisk og regelmessig en sanitized database?

### ISSUE THREAD

**Issue by truls1502** [drupalnorge/drupalnorge-social#174]
Hvordan eksporteres automatisk og regelmessig en sanitized database?

Er det noe vi kan få til med **cron** med **drush** eller lage en sånn egen **script**? Kan man kombinere med _sqlsan_ og _sql-dump_? Noen som har ide? 

Jeg tenke at vi kunne slippe å gjøre manuelt ved å duplikate DB, sql-sanitize den, deretter dump og overfør den til drupalnorge.no/sanitized.db - enig?

**Comment by truls1502** [comment]
How about something like it in cron: `drush sql-sync @source @target && drush @target sql-dump --result-file=/html/sanitized.db && drush sql-drop @target`?

**Comment by eiriksm** [comment]
Dette fungerer i teorien. Det krever to databaser. Men I det miljøet drupalnorge kjører, så er det bare en database.

Uansett, jeg skal få satt opp dette på en annen server. Lar denne stå åpen til jeg har fått satt det opp :)

**Comment by truls1502** [comment]
Skal se om jeg finner noe omvei som ikke trenger å bruke en ekstra database, men direkte dump og sanitized.

**Comment by eiriksm** [comment]
Det går fint, jeg fikser dette :)

**Comment by eiriksm** [comment]
Det blir nå eksportert en sanitized database hver morgen kl 0750
