### ISSUE TITLE
crash on search string 

### ISSUE THREAD

**Issue by AurSol** [drupalnorge/drupalnorge-social#19]
search string used: chart 

error output:

Det oppstod en uventet feil på nettstedet. Prøv igjen seinere.

Symfony\Component\Routing\Exception\RouteNotFoundException: Route "view.search_groups.page" does not exist. in Drupal\Core\Routing\RouteProvider->getRouteByName() (line 187 of core/lib/Drupal/Core/Routing/RouteProvider.php).
Drupal\Core\Menu\LocalTaskDefault->getRouteParameters(Object) (Line: 310)
Drupal\Core\Menu\LocalTaskManager->getTasksBuild('view.search_content.page', Object) (Line: 358)
Drupal\Core\Menu\LocalTaskManager->getLocalTasks('view.search_content.page', 0) (Line: 94)
Drupal\Core\Menu\Plugin\Block\LocalTasksBlock->build() (Line: 203)
Drupal\block\BlockViewBuilder::preRender(Array)
call_user_func('Drupal\block\BlockViewBuilder::preRender', Array) (Line: 376)
Drupal\Core\Render\Renderer->doRender(Array) (Line: 448)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array) (Line: 468)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 84)
__TwigTemplate_aebd0f6e35ab8f97dc3faa8d47ea7b1cf63078297f60bbe47352daf625b156fe->doDisplay(Array, Array) (Line: 396)
Twig_Template->displayWithErrorHandling(Array, Array) (Line: 364)
Twig_Template->display(Array) (Line: 375)
Twig_Template->render(Array) (Line: 64)
twig_render_template('profiles/contrib/social/themes/socialbase/templates/layout/page.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('page', Array) (Line: 435)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array) (Line: 468)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 93)
__TwigTemplate_57c5aef71d25fc70104af0e339f0f51e9313cd092de009415fd74aa7d98b089b->doDisplay(Array, Array) (Line: 396)
Twig_Template->displayWithErrorHandling(Array, Array) (Line: 364)
Twig_Template->display(Array) (Line: 375)
Twig_Template->render(Array) (Line: 64)
twig_render_template('profiles/contrib/social/themes/socialbase/templates/system/html.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('html', Array) (Line: 435)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array) (Line: 147)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 574)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 148)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object) (Line: 149)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 64)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 654)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

**Comment by eiriksm** [comment]
Updated to latest version. This does not seem to be a problem any more
