### ISSUE TITLE
Unexpected error on login

### ISSUE THREAD

**Issue by thorandre** [drupalnorge/drupalnorge-social#236]
Noen kollegaer av meg prøvde å logge seg inn å drupalnorge.no idag, og får "Unexpected error" ved innlogging. Deretter får de unexpected error på alle andre sider også.

**Comment by truls1502** [comment]
@thorandre - har du/dere et skjermbilde eller noe informasjon fra console? Får du logget inn med din egen bruker? Hvis ja, kan du sende PM på slack hvilket bruker som får feilmedlingen? 😊

**Comment by truls1502** [comment]
Jeg lukker den issue da det ser ut som den ikke er lengre et problem 😊Hvis du/dere opplever fortsatt samme, så er det bare å åpne igjen denne issuen. 😉
