### ISSUE TITLE
/all-topics og /all-members eksisterer ikke

### ISSUE THREAD

**Issue by hansfn** [drupalnorge/drupalnorge-social#36]
I menyen Hovednavigasjon, som et underpunkt til Utforsk, så er det en lenke "Alle lenker" (All Topics) som er død. Manglende View eller feilkonfigurert?

**Comment by hansfn** [comment]
Ja, "Alle medlemmer" (All members) er også død.

**Comment by thorandre** [comment]
Ser at verken "Alle medlemmer" eller "Alle topics" har noe view. Deaktiverer "Alle emner"-lenken (det finnes pr nå kun ett emne). Endrer lenken til alle medlemmer til /newest-members som fungerer, selv om listen ikke er perfekt da den kun viser 4 brukere pr side.
